//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TVAlertLogScanningDelay {
            get {
                return ((int)(this["TVAlertLogScanningDelay"]));
            }
            set {
                this["TVAlertLogScanningDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiscordAlertsEnabled {
            get {
                return ((bool)(this["DiscordAlertsEnabled"]));
            }
            set {
                this["DiscordAlertsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiscordAlertsUseScreenshot {
            get {
                return ((bool)(this["DiscordAlertsUseScreenshot"]));
            }
            set {
                this["DiscordAlertsUseScreenshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordAlertBotToken {
            get {
                return ((string)(this["DiscordAlertBotToken"]));
            }
            set {
                this["DiscordAlertBotToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordAlertGuildServerId {
            get {
                return ((string)(this["DiscordAlertGuildServerId"]));
            }
            set {
                this["DiscordAlertGuildServerId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordAlertTextChannelId {
            get {
                return ((string)(this["DiscordAlertTextChannelId"]));
            }
            set {
                this["DiscordAlertTextChannelId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiscordAlertTagHere {
            get {
                return ((bool)(this["DiscordAlertTagHere"]));
            }
            set {
                this["DiscordAlertTagHere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiscordAlertTagEveryone {
            get {
                return ((bool)(this["DiscordAlertTagEveryone"]));
            }
            set {
                this["DiscordAlertTagEveryone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitterAlertsEnabled {
            get {
                return ((bool)(this["TwitterAlertsEnabled"]));
            }
            set {
                this["TwitterAlertsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitterAlertsUseScreenshot {
            get {
                return ((bool)(this["TwitterAlertsUseScreenshot"]));
            }
            set {
                this["TwitterAlertsUseScreenshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitterAlertsConsumerKey {
            get {
                return ((string)(this["TwitterAlertsConsumerKey"]));
            }
            set {
                this["TwitterAlertsConsumerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitterAlertsConsumerSecret {
            get {
                return ((string)(this["TwitterAlertsConsumerSecret"]));
            }
            set {
                this["TwitterAlertsConsumerSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitterAlertsAccessToken {
            get {
                return ((string)(this["TwitterAlertsAccessToken"]));
            }
            set {
                this["TwitterAlertsAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitterAlertsAccessTokenSecret {
            get {
                return ((string)(this["TwitterAlertsAccessTokenSecret"]));
            }
            set {
                this["TwitterAlertsAccessTokenSecret"] = value;
            }
        }
    }
}
